const hostels = [
  {
    name: "Sukh PG",
    gender: "Male",
    hostelType: "Men",
    address: "1-10-30,Ameerpet, Hyderabad, India",
    price: "₹4000/month",
    description:
      "A budget-friendly PG with clean rooms and all essential services for men.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Offices",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Power Backup",
    ],
    roomSharing: "2,3,4,5",
    rating: 3.5,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Akash Nivas",
    gender: "Female",
    hostelType: "Women",
    address: "2-3-88, Malkajgiri, Hyderabad, India",
    price: "₹7500/month",
    description:
      "A luxurious hostel for girls with modern facilities and great amenities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Metro",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Gym",
    ],
    roomSharing: "2,3,4",
    rating: 4.7,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://thumbs.dreamstime.com/b/backpackers-hostel-modern-bunk-beds-dorm-room-twelve-people-inside-79935795.jpg",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Nagari Dham",
    gender: "Male",
    hostelType: "Men",
    address: "3-6-340, Banjara Hills, Hyderabad, India",
    price: "₹6000/month",
    description:
      "A premium hostel for men offering excellent services and great amenities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Park",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Barbecue Area",
    ],
    roomSharing: "3,4,5",
    rating: 4.2,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Nagar Aavas",
    gender: "Male",
    hostelType: "Men",
    address: "5-4-344, Ameerpet, Hyderabad, India",
    price: "₹5200/month",
    description:
      "Modern living space for men, offering convenience and comfort.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Downtown",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Gym",
    ],
    roomSharing: "2,3,4",
    rating: 4.0,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Hari Meadows PG",
    gender: "Female",
    hostelType: "Women",
    address: "7-1-21, Kukatpally, Hyderabad, India",
    price: "₹4800/month",
    description:
      "A peaceful and eco-friendly environment with modern amenities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable to Metro Station",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Eco-Friendly Practices",
    ],
    roomSharing: "2,4,6",
    rating: 4.1,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Shreshtha Gateway Hostel",
    gender: "Male",
    hostelType: "Men",
    address: "8-2-684, Road No. 12, Banjara Hills, Hyderabad, India",
    price: "₹6000/month",
    description:
      "A luxurious, well-maintained hostel for working professionals.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Office Area",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Sports Area",
    ],
    roomSharing: "2,3,4",
    rating: 4.5,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Ravi Nivas",
    gender: "Female",
    hostelType: "Women",
    address: "1-1-214, Nallakunta, Hyderabad, India",
    price: "₹6500/month",
    description:
      "A bright and cheerful place for women with top-notch facilities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Shops",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Game Room",
    ],
    roomSharing: "2,3",
    rating: 4.6,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Sukoon PG",
    gender: "Male",
    hostelType: "Men",
    address: "4-2-51, Narayanguda, Hyderabad, India",
    price: "₹5500/month",
    description:
      "A comfortable and secure space for men, with all the necessary amenities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Park",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "24/7 Security",
    ],
    roomSharing: "3,4",
    rating: 4.3,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Parvat PG",
    gender: "Female",
    hostelType: "Women",
    address: "10-2-15, Basheerbagh, Hyderabad, India",
    price: "₹7000/month",
    description:
      "A peaceful hostel located on the hilltop, offering serenity and convenience.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to City Center",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Library",
    ],
    roomSharing: "2,3",
    rating: 4.0,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Samudra Breeze Hostel",
    gender: "Male",
    hostelType: "Men",
    address: "6-3-565, Raj Bhavan Road, Hyderabad, India",
    price: "₹6200/month",
    description:
      "A seaside hostel offering a relaxed atmosphere and great amenities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable to Beach",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Beach Sports Area",
    ],
    roomSharing: "3,5",
    rating: 4.4,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Vriksha Hostel",
    gender: "Female",
    hostelType: "Women",
    address: "2-4-470, Ramnagar, Hyderabad, India",
    price: "₹5800/month",
    description: "A charming hostel for women surrounded by lush greenery.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Nature Trails",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Outdoor Garden",
    ],
    roomSharing: "2,3,4,5,6",
    rating: 4.2,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Surya View PG",
    gender: "Male",
    hostelType: "Men",
    address: "1-2-111, Park Lane, Hyderabad, India",
    price: "₹5200/month",
    description: "A hostel with beautiful sunset views and affordable rates.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable to Waterfront",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "BBQ Area",
    ],
    roomSharing: "2,3,4,5",
    rating: 4.1,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  // Add more hostels here...
  {
    name: "Sukhi Stay Hostel",
    gender: "Male",
    hostelType: "Men",
    address: "3-5-143, Sardar Patel Road, Hyderabad, India",
    price: "₹5000/month",
    description:
      "A comfortable and peaceful hostel for students with all modern amenities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Bus Stand",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "24/7 Security",
    ],
    roomSharing: "2,3,4,5",
    rating: 4.5,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Neelkamal Nivas",
    gender: "Female",
    hostelType: "Women",
    address: "7-4-34, Langar Houz, Hyderabad, India",
    price: "₹5500/month",
    description:
      "A safe and secure hostel for girls with spacious rooms and great facilities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Market",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "24/7 Security",
    ],
    roomSharing: "2,3,4,6",
    rating: 4.8,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Raj PG",
    gender: "Male",
    hostelType: "Men",
    address: "9-2-104, Shaikpet, Hyderabad, India",
    price: "₹4000/month",
    description:
      "Affordable PG for working professionals with all necessary amenities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable to Office",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Power Backup",
    ],
    roomSharing: "3,4,5",
    rating: 3.5,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Aram Kendra",
    gender: "Female",
    hostelType: "Women",
    address: "1-3-123, Chikkadpally, Hyderabad, India",
    price: "₹6000/month",
    description:
      "A cozy hostel with a homely atmosphere, ideal for students and working women.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Station",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Cleaning Services",
    ],
    roomSharing: "2,3,",
    rating: 4.0,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Elite Nivas",
    gender: "Male",
    hostelType: "Men",
    address: "2-1-65, Moosarambagh, Hyderabad, India",
    price: "₹6500/month",
    description:
      "A luxurious hostel for men offering modern facilities and a comfortable environment.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Metro",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Gym",
    ],
    roomSharing: "2,3,4,6",
    rating: 4.9,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Surya Hostel",
    gender: "Female",
    hostelType: "Women",
    address: "4-6-189, Dilsukhnagar, Hyderabad, India",
    price: "₹7000/month",
    description:
      "A beautiful and peaceful hostel for girls, located in the heart of Pune.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to City Center",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Library",
    ],
    roomSharing: "2,3,4",
    rating: 4.3,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Shanti PG",
    gender: "Male",
    hostelType: "Men",
    address: "10-2-25, Lakdikapul, Hyderabad, India",
    price: "₹4500/month",
    description:
      "A budget-friendly hostel for students and professionals with all essential services.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable to Universities",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Air Conditioning",
    ],
    roomSharing: "2,3,4",
    rating: 4.1,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Shanti Sadan",
    gender: "Female",
    hostelType: "Women",
    address: "6-1-16, Secunderabad, Hyderabad, India",
    price: "₹5500/month",
    description:
      "A peaceful hostel for girls offering a homely environment and good facilities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable to Bus Stop",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Yoga Room",
    ],
    roomSharing: "2,3,4",
    rating: 4.2,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Triveni PG",
    gender: "Male",
    hostelType: "Men",
    address: "3-7-258, Aghapura, Hyderabad, India",
    price: "₹4500/month",
    description:
      "A serene and affordable PG for men with all necessary amenities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Lake",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Power Backup",
    ],
    roomSharing: "2,3,4,6",
    rating: 4.1,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Anand Nivas",
    gender: "Female",
    hostelType: "Women",
    address: "7-6-121, Sainikpuri, Hyderabad, India",
    price: "₹5500/month",
    description:
      "A safe and secure hostel for women with spacious rooms and modern facilities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Market",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "24/7 Security",
    ],
    roomSharing: "2,3,4,5",
    rating: 4.4,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Shanti Niketan",
    gender: "Male",
    hostelType: "Men",
    address: "8-4-118, Toli Chowki, Hyderabad, India",
    price: "₹4000/month",
    description:
      "A budget-friendly hostel for students with a peaceful environment.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Garden",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Library",
    ],
    roomSharing: "2,4,5",
    rating: 3.8,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Seva Sadan",
    gender: "Female",
    hostelType: "Women",
    address: "5-2-120, Malakpet, Hyderabad, India",
    price: "₹6000/month",
    description:
      "A cozy hostel with a homely atmosphere, ideal for students and working women.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Hill",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4,",
    rating: 4.5,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Prithvi Nivas",
    gender: "Male",
    hostelType: "Men",
    address: "9-6-71, Mehdipatnam, Hyderabad, India",
    price: "₹6500/month",
    description:
      "A luxurious hostel for men offering modern facilities and a comfortable environment.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Metro",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Gym",
    ],
    roomSharing: "2,3,4,",
    rating: 4.7,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Swapna Hostel",
    gender: "Female",
    hostelType: "Women",
    address: "1-5-422, Osmania University Road, Hyderabad, India",
    price: "₹7000/month",
    description:
      "A beautiful and peaceful hostel for girls, located in the heart of Bhopal.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to City Center",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Library",
    ],
    roomSharing: "2,3,4",
    rating: 4.2,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Aman PG",
    gender: "Male",
    hostelType: "Men",
    address: "3-8-152, KPHB, Hyderabad, India",
    price: "₹4500/month",
    description:
      "A budget-friendly hostel for students and professionals with all essential services.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable to Universities",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Air Conditioning",
    ],
    roomSharing: "2,3,4,5",
    rating: 4.0,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Shree Niketan",
    gender: "Female",
    hostelType: "Women",
    address: "4-5-31, Gachibowli, Hyderabad, India",
    price: "₹5500/month",
    description:
      "A peaceful hostel for girls offering a homely environment and good facilities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable to Bus Stop",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Yoga Room",
    ],
    roomSharing: "2,3,4,",
    rating: 4.3,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Krishna PG",
    gender: "Male",
    hostelType: "Men",
    address: "7-2-35, Banjara Hills, Hyderabad, India",
    price: "₹5000/month",
    description:
      "A serene PG for men with clean rooms and all essential amenities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to River",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Power Backup",
    ],
    roomSharing: "2,3,4,",
    rating: 4.1,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Navya Hostel",
    gender: "Female",
    hostelType: "Women",
    address: "2-7-274, Malkajgiri, Hyderabad, India",
    price: "₹6000/month",
    description:
      "A cozy hostel for women with spacious rooms and modern amenities.",
    services: [
      "Reception",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Park",
      "Elevator",
      "Luggage Rack",
      "Wi-Fi",
      "TV",
      "Washing Machine",
      "Homely Food (Non-Veg Twice a Week)",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4,",
    rating: 4.4,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Sunrise PG",
    gender: "Female",
    hostelType: "Women",
    address: "6-4-84, Khairatabad, Hyderabad, India",
    price: "₹5800/month",
    description: "A modern hostel for women with all essential amenities.",
    services: [
      "Reception",
      "Wi-Fi",
      "Laundry",
      "CCTV Camera",
      "Hot Water",
      "Security",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.1,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "The Comfort Hostel",
    gender: "Male",
    hostelType: "Men",
    address: "5-3-110, Madhapur, Hyderabad, India",
    price: "₹6000/month",
    description: "Spacious rooms and a quiet environment for men.",
    services: [
      "Reception",
      "Wi-Fi",
      "Hot Water",
      "Laundry",
      "Security",
      "CCTV Camera",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.3,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Royal PG",
    gender: "Female",
    hostelType: "Women",
    address: "3-5-143, Sardar Patel Road, Hyderabad, India",
    price: "₹6500/month",
    description: "A premium PG for women with high-end facilities.",
    services: [
      "Reception",
      "Wi-Fi",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Walkable Distance to Park",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.6,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Sree Sai Residency",
    gender: "Male",
    hostelType: "Men",
    address: "4-9-54, Kukatpally, Hyderabad, India",
    price: "₹5500/month",
    description: "Comfortable and secure PG for men with great accessibility.",
    services: [
      "Reception",
      "Wi-Fi",
      "Hot Water",
      "Laundry",
      "Security",
      "CCTV Camera",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.4,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Greenfield PG",
    gender: "Female",
    hostelType: "Women",
    address: "7-1-21, Kukatpally, Hyderabad, India",
    price: "₹6300/month",
    description:
      "A peaceful and safe place for women with all modern amenities.",
    services: [
      "Reception",
      "Wi-Fi",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Elevator",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.5,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Madhur PG",
    gender: "Male",
    hostelType: "Men",
    address: "9-2-104, Shaikpet, Hyderabad, India",
    price: "₹5700/month",
    description: "A budget-friendly PG with great amenities.",
    services: [
      "Reception",
      "Wi-Fi",
      "Laundry",
      "Hot Water",
      "Security",
      "CCTV Camera",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.0,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Elite PG",
    gender: "Female",
    hostelType: "Women",
    address: "1-10-30, Himayat Nagar, Hyderabad, India",
    price: "₹6900/month",
    description: "An elite PG with all amenities and premium facilities.",
    services: [
      "Reception",
      "Wi-Fi",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Security",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.7,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Srinivasa PG",
    gender: "Male",
    hostelType: "Men",
    address: "10-4-45, LB Nagar, Hyderabad, India",
    price: "₹5500/month",
    description: "A peaceful and affordable PG for men.",
    services: [
      "Reception",
      "Wi-Fi",
      "Hot Water",
      "Laundry",
      "Security",
      "CCTV Camera",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.2,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Breeze PG",
    gender: "Female",
    hostelType: "Women",
    address: "3-7-258, Aghapura, Hyderabad, India",
    price: "₹6200/month",
    description:
      "A welcoming and comfortable PG for women with modern facilities.",
    services: [
      "Reception",
      "Wi-Fi",
      "Laundry",
      "CCTV Camera",
      "Hot Water",
      "Elevator",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.4,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Arya PG",
    gender: "Male",
    hostelType: "Men",
    address: "2-3-88, Malkajgiri, Hyderabad, India",
    price: "₹6000/month",
    description: "A comfortable and spacious PG for men.",
    services: [
      "Reception",
      "Wi-Fi",
      "Hot Water",
      "Laundry",
      "Security",
      "CCTV Camera",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.3,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Royal Elite Hostel",
    gender: "Female",
    hostelType: "Women",
    address: "6-9-18, Nampally, Hyderabad, India",
    price: "₹6700/month",
    description:
      "Premium women's hostel with modern features and high security.",
    services: [
      "Reception",
      "Wi-Fi",
      "CCTV Camera",
      "Hot Water",
      "Laundry",
      "Elevator",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.6,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Comfort Zone PG",
    gender: "Male",
    hostelType: "Men",
    address: "9-3-78, Begumpet, Hyderabad, India",
    price: "₹5400/month",
    description:
      "Affordable PG with all basic amenities and a secure environment.",
    services: [
      "Reception",
      "Wi-Fi",
      "Laundry",
      "Security",
      "CCTV Camera",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.0,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Happy Stay PG",
    gender: "Female",
    hostelType: "Women",
    address: "4-2-51, Narayanguda, Hyderabad, India",
    price: "₹6400/month",
    description: "A cheerful PG with friendly services and facilities.",
    services: [
      "Reception",
      "Wi-Fi",
      "Laundry",
      "CCTV Camera",
      "Hot Water",
      "Elevator",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.2,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Comfort PG",
    gender: "Male",
    hostelType: "Men",
    address: "3-6-340, Banjara Hills, Hyderabad, India",
    price: "₹6100/month",
    description: "Comfortable and homely environment for men.",
    services: [
      "Reception",
      "Wi-Fi",
      "Laundry",
      "Security",
      "CCTV Camera",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.3,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Shubham PG",
    gender: "Male",
    hostelType: "Men",
    address: "8-2-684, Road No. 12, Banjara Hills, Hyderabad, India",
    price: "₹5900/month",
    description: "Well-kept and secure PG with great accessibility.",
    services: [
      "Reception",
      "Wi-Fi",
      "Laundry",
      "Security",
      "CCTV Camera",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.1,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "Elite Ladies Hostel",
    gender: "Female",
    hostelType: "Women",
    address: "7-10-222, Kukatpally, Hyderabad, India",
    price: "₹6800/month",
    description: "A premium women's hostel with secure and spacious rooms.",
    services: [
      "Reception",
      "Wi-Fi",
      "Laundry",
      "CCTV Camera",
      "Hot Water",
      "Security",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.5,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
  {
    name: "The Regency PG",
    gender: "Male",
    hostelType: "Men",
    address: "5-2-34, Jambagh, Hyderabad, India",
    price: "₹6600/month",
    description: "A luxurious PG for men with all essential amenities.",
    services: [
      "Reception",
      "Wi-Fi",
      "Laundry",
      "Hot Water",
      "Security",
      "CCTV Camera",
      "Cleaning Services",
    ],
    roomSharing: "2,3,4",
    rating: 4.6,
    availableRooms: Math.floor(Math.random() * 25),
    images: [
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
      "https://via.placeholder.com/300",
    ],
  },
];

export default hostels;

// const hostels = [
//   {
//     name: "Sukh PG",
//     gender: "Male",
//     hostelType: "Men",
//     address: "Madhapur, Hyderabad, India",
//     price: "₹4000/month",
//     description:
//       "A budget-friendly PG with clean rooms and all essential services for men.",
//     services: [
//       "Reception",
//       "CCTV Camera",
//       "Hot Water",
//       "Laundry",
//       "Walkable Distance to Offices",
//       "Elevator",
//       "Luggage Rack",
//       "Wi-Fi",
//       "TV",
//       "Washing Machine",
//       "Homely Food (Non-Veg Twice a Week)",
//       "Power Backup",
//     ],
//     roomSharing: "2,3,4,5",
//     rating: 3.5,
//     availableRooms: Math.floor(Math.random() * 25),
//     images: [
//       "https://via.placeholder.com/300",
//       "https://via.placeholder.com/300",
//       "https://via.placeholder.com/300",
//     ],
//   },
//   {
//     name: "Elite Stay PG",
//     gender: "Male",
//     hostelType: "Men",
//     address: "Gachibowli, Hyderabad, India",
//     price: "₹5000/month",
//     description:
//       "A premium hostel for men with all modern amenities and easy access to IT hubs.",
//     services: [
//       "Reception",
//       "CCTV Camera",
//       "Hot Water",
//       "Laundry",
//       "Elevator",
//       "Wi-Fi",
//       "TV",
//       "Washing Machine",
//       "Power Backup",
//     ],
//     roomSharing: "2,3,4",
//     rating: 4.2,
//     availableRooms: Math.floor(Math.random() * 25),
//     images: [
//       "https://via.placeholder.com/300",
//       "https://via.placeholder.com/300",
//       "https://via.placeholder.com/300",
//     ],
//   },
//   {
//     name: "Green Nest PG",
//     gender: "Female",
//     hostelType: "Women",
//     address: "Kondapur, Hyderabad, India",
//     price: "₹6000/month",
//     description:
//       "A secure and comfortable stay for women, with homely food and a peaceful environment.",
//     services: [
//       "Reception",
//       "CCTV Camera",
//       "Hot Water",
//       "Laundry",
//       "Wi-Fi",
//       "TV",
//       "Washing Machine",
//       "Power Backup",
//       "24/7 Security",
//     ],
//     roomSharing: "2,3",
//     rating: 4.5,
//     availableRooms: Math.floor(Math.random() * 25),
//     images: [
//       "https://via.placeholder.com/300",
//       "https://via.placeholder.com/300",
//       "https://via.placeholder.com/300",
//     ],
//   },
//   // 51 more hostel objects
//   ...Array.from({ length: 51 }, (_, i) => ({
//     name: `Hostel ${i + 4}`,
//     gender: i % 2 === 0 ? "Male" : "Female",
//     hostelType: i % 2 === 0 ? "Men" : "Women",
//     address: `${
//       [
//         "Madhapur",
//         "Hitech City",
//         "Gachibowli",
//         "Jubilee Hills",
//         "Banjara Hills",
//         "Kukatpally",
//         "Ameerpet",
//         "Begumpet",
//         "Mehdipatnam",
//         "Secunderabad",
//         "Charminar",
//         "Tarnaka",
//         "Kompally",
//         "Dilsukhnagar",
//         "LB Nagar",
//         "Miyapur",
//         "Manikonda",
//         "Kondapur",
//         "Attapur",
//         "Shamshabad",
//         "Abids",
//         "Nallagandla",
//         "Chandanagar",
//         "Tolichowki",
//         "Moosapet",
//         "Nagole",
//         "Uppal",
//         "Malakpet",
//       ][i % 5]
//     }, Hyderabad, India`,
//     price: `₹${4000 + (i % 5) * 1000}/month`,
//     description: "A well-maintained hostel with modern amenities and security.",
//     services: [
//       "Reception",
//       "CCTV Camera",
//       "Hot Water",
//       "Laundry",
//       "Wi-Fi",
//       "TV",
//       "Washing Machine",
//       "Power Backup",
//       "24/7 Security",
//       "Walkable Distance to Metro",
//       "Elevator",
//       "Luggage Rack",
//       "Homely Food (Non-Veg Twice a Week)",
//       "Gym",
//     ],
//     roomSharing: "2,3,4",
//     rating: (3.5 + (i % 3) * 0.5).toFixed(1),
//     availableRooms: Math.floor(Math.random() * 25),
//     images: [
//       "https://via.placeholder.com/300",
//       "https://via.placeholder.com/300",
//       "https://via.placeholder.com/300",
//     ],
//   })),
// ];

// export default hostels;
